name: 'CD'

on:
    push:
        branches:
            - main

jobs:
    wat:
        name: wat
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set LAST_CHANGELOG_ENTRY
              id: set-last-changelog-entry
              run: |
                # read from the first until the second header in the changelog file
                # this assumes the formatting of the file
                # and that this workflow is always running for the most recent entry in the file 
                LAST_CHANGELOG_ENTRY=$(awk -v defText="see CHANGELOG.md" '/^## /{if (flag) exit; flag=1} flag && /^##$/{exit} flag; END{if (!flag) print defText}' CHANGELOG.md | base64)
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer secrets.GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/posthog/posthog-js/releases \
                -d '{"tag_name":"v1.0.0444","target_commitish":"main","name":"v1.0.0444","body":$LAST_CHANGELOG_ENTRY,"draft":false,"prerelease":false,"generate_release_notes":false}'
