name: 'CD'

on:
    push:
        branches:
            - main

jobs:
    wat:
        name: wat
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set LAST_CHANGELOG_ENTRY
              id: set-last-changelog-entry
              run: |
                # read from the first until the second header in the changelog file
                # this assumes the formatting of the file
                # and that this workflow is always running for the most recent entry in the file 
                ENCODED_CONTENT=$(awk -v defText="see CHANGELOG.md" '/^## /{if (flag) exit; flag=1} flag && /^##$/{exit} flag; END{if (!flag) print defText}' CHANGELOG.md | base64)
                echo "LAST_CHANGELOG_ENTRY=$ENCODED_CONTENT" >> "$GITHUB_OUTPUT"
                echo "we generated ${LAST_CHANGELOG_ENTRY}"

            - name: checkit
              run: |
                echo ${{ steps.set-last-changelog-entry.outputs.LAST_CHANGELOG_ENTRY }}
                  
            - name: Create GitHub release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v101
                  release_name: first
                  body: ${{ $(echo "${{ steps.set-last-changelog-entry.outputs.LAST_CHANGELOG_ENTRY }}" | base64 --decode) }}
