name: 'CD'

on:
    push:
        branches:
            - main

jobs:
    wat:
        permissions:
          contents: write
        name: wat
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set LAST_CHANGELOG_ENTRY
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              id: set-last-changelog-entry
              run: |
                # read from the first until the second header in the changelog file
                # this assumes the formatting of the file
                # and that this workflow is always running for the most recent entry in the file 
                LAST_CHANGELOG_ENTRY=$(awk -v defText="see CHANGELOG.md" '/^## /{if (flag) exit; flag=1} flag && /^##$/{exit} flag; END{if (!flag) print defText}' CHANGELOG.md)
                gh api \
                  --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/pauldambra/posthog-js-fork-for-changelog-cd/releases \
                  -f tag_name='v1.0.055as5' \
                -f target_commitish='main' \
                -f name='v1.0.044sdasd44' \
                -f body="$LAST_CHANGELOG_ENTRY" \
                -F draft=false \
                -F prerelease=false \
                -F generate_release_notes=false 
